title: "Rohit Das - Java Developer"
description: "Portfolio and Resume of Rohit Das"
show_downloads: false
google_analytics: ""

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

github:
  url: "https://github.com/yourusername"
